# Name des Workflows
name: Cordova iOS Build

# Wann soll der Workflow ausgelöst werden?
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definition der Jobs, die ausgeführt werden sollen
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      # Holt den Code aus dem Repository
      uses: actions/checkout@v4

    - name: Install Node.js
      # Richtet Node.js ein, was für Cordova benötigt wird
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Cordova CLI
      # Installiert die Cordova-Befehlszeilen-Tools global
      run: npm install -g cordova

    - name: Install Dependencies
      # Installiert die Abhängigkeiten deines Projekts
      run: npm install

    - name: Add Cordova iOS Platform
      # DIES IST DER NEUE, WICHTIGE SCHRITT.
      # Dieser Befehl fügt die iOS-Plattform zu dem Projekt auf dem virtuellen Mac-Computer hinzu.
      run: cordova platform add ios --no-fetch
      
    - name: Cordova iOS Build
      # Führt den Cordova-Build-Befehl für die iOS-Plattform aus
      run: cordova build ios --emulator --release
      
    - name: Upload iOS App as Artifact
      # Lädt die App-Datei als Artefakt hoch
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-build
        path: platforms/ios/build/emulator
